Project/mealPlanner/src/Entity/Meals.php
<?php

namespace App\Entity;

use App\Repository\MealsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MealsRepository::class)
 */
class Meals
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_time;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="meals")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_user_id;

    /**
     * @ORM\ManyToOne(targetEntity=Dishes::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_dish_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): self
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getFkUserId(): ?User
    {
        return $this->fk_user_id;
    }

    public function setFkUserId(?User $fk_user_id): self
    {
        $this->fk_user_id = $fk_user_id;

        return $this;
    }

    public function getFkDishId(): ?Dishes
    {
        return $this->fk_dish_id;
    }

    public function setFkDishId(?Dishes $fk_dish_id): self
    {
        $this->fk_dish_id = $fk_dish_id;

        return $this;
    }
}

Project/mealPlanner/src/Controller/ScheduleMealsController.php
<?php

namespace App\Controller;

use App\Entity\Meals;
use App\Entity\Dishes;
use App\Entity\Users;
use App\Form\MealsType;
use App\Repository\MealsRepository;
use App\Repository\DishesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\Validator\Constraints\DateTimeValidator;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

#[Route('/schedule/meals')]
class ScheduleMealsController extends AbstractController
{
    #[Route('/', name: 'schedule_meals_index', methods: ['GET'])]
    public function index(MealsRepository $mealsRepository): Response
    {


        $conn = $this->getDoctrine()->getManager()->getConnection();

        $sql = '
        SELECT meals.date_time, meals.id, meals.fk_dish_id_id, dishes.dish_name, dishes.image, meals.fk_user_id_id FROM meals JOIN dishes on meals.fk_dish_id_id = dishes.id
            ';

        $stmt = $conn->prepare($sql);
        $stmt->execute();
        $result = $stmt->fetchAllAssociative();

        // $meals = $mealsRepository->findAll();
        // $em = $this->getDoctrine()->getManager();
        // $query = $em->createQueryBuilder();
        // //         ->select('m', 'd')
        // //         ->join('dishes', 'd', 'm.fk_dish_id = d.dish_id')
        // //         // ->where('meals.fk_dish_id = d.dish_id')
        // //         ->getQuery()->getResult();

        // $query->select(array('m', 'd'))
        // ->from('Meals', 'm')
        // ->innerJoin('Dishes', 'd', 'm.fk_dish_id = d.dish_id');

        // $result = $query->getQuery();

        // $query = $em->createQuery("SELECT dishes.dish_name dishes.image meals.id meals.fk_user_id meals.fk_dish_id meals.date_time FROM 'app\Entity\Meals' meals JOIN app\Entity\Dishes dishes");
        // $result = $query->getResult();

        // dd($result);

            // $today = new \DateTime();

           


            $days = array();

            function calDays(){
                $days = array();
                for($i = 0; $i < 7; $i++){

                    $day = new \DateTime('now +'.$i.' day');
                    $day = $day->format('d-m-Y');
                    array_push( $days , $day);
                }
                return $days;
            }

          
            $bf_s = array();
            function times($time, $var){
                $days = array();
                for($i = 0; $i < 7; $i++){
                    $day = new \DateTime('now +'.$i.' day');
                    $day = $day->format('d-m-Y');
                    array_push( $days , $day);
                }
                
                $var = array();
                foreach($days as $day){

                    $data = $day.' '.$time;
                    array_push($var, $data);

                }
                return $var;
            }

            $breakfast_s = '05:00:00';
            $b_s = array();

            $lunch_s = '12:00:00';
            $l_s = array();

            $dinner_s = '19:00:00';
            $d_s = array();

            $night_s = '23:00:00';
            $n_s = array();


            calDays();
            times($breakfast_s, $b_s);
            times($lunch_s, $l_s);
            times($dinner_s, $d_s);
            times($night_s, $n_s);


            // THIS IS ONLY TO SHOW THE TWIG LOGIC!!! THIS SOLUTION WOULD NEED HARD CODING
            $today = new \DateTime();
            $day1 = $today->format('Y-m-d');   
            $today = $today->format('Y-m-d');
            // END OF EVIL HARD CODING SOLUTION

            // dd($today.$dinner_s);


            return $this->render('schedule_meals/index.html.twig', [
            'meals' => $mealsRepository->findAll(),
            'result' => $result,
            'today' => $day1,
            'breakfast_start' => $today.' '.$breakfast_s,
            'lunch_start' => $today.' '.$lunch_s,
            'dinner_start' => $today.' '.$dinner_s,
            'night_start' => $today.' '.$night_s,
            'days' => $days,
            'b_time' => $b_s,
            'l_time' => $l_s,
            'd_time' => $d_s,
            'n_time' => $n_s,

            

        ]);
    }

    #[Route('/new', name: 'schedule_meals_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {


        $user = $this->getUser();
        $meal = new Meals();
        $form = $this->createFormBuilder($meal)
        ->add("date_time", DateTimeType::class, array('attr' => array("class" => "form-control", "style" => "margin-bottom: 15px;"),'input' => 'datetime',
        'data' => new \DateTime(),
        'minutes' => array(
           0, 15, 30, 45
        ),  'label' => 'Choose the date and time',))
        ->add('fk_dish_id', EntityType::class, ['attr' => array("class" => "form-control", "style" => "margin-bottom: 15px;"),'class' => Dishes::class, 'choice_label' => 'dish_name', 'label' => 'Pick a dish'])

        ->add("save", SubmitType::class, array('attr' => array("class" => "btn btn-success", "style" => "margin-bottom: 15px; margin-top: 15px;"), "label" => "Submit"))->getForm();



        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $date_time = $form["date_time"]->getData();
            $fk_user_id = $user;
            $fk_dish_id = $form["fk_dish_id"]->getData();

            $meal->setDateTime($date_time);
            $meal->setFkUserId($fk_user_id);
            $meal->setFkDishId($fk_dish_id);
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($meal);
            $entityManager->flush();



            return $this->redirectToRoute('schedule_meals_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('schedule_meals/new.html.twig', [
            'meal' => $meal,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'schedule_meals_show', methods: ['GET'])]
    public function show(Meals $meal): Response
    {
        return $this->render('schedule_meals/show.html.twig', [
            'meal' => $meal,
        ]);
    }

    #[Route('/{id}/edit', name: 'schedule_meals_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Meals $meal): Response
    {

        
        
        $user = $this->getUser();
     
        $form = $this->createFormBuilder($meal)
        ->add("date_time", DateTimeType::class, array('attr' => array("class" => "form-control", "style" => "margin-bottom: 15px;")))

        ->add('fk_dish_id', EntityType::class, [ 'attr' => array("class" => "form-control", "style" => "margin-bottom: 15px;"), 'class' => Dishes::class, 'choice_label' => 'dish_name', 'label' => 'Pick a dish'])

        ->add("save", SubmitType::class, array('attr' => array("class" => "btn btn-success", "style" => "margin-bottom: 15px; margin-top: 15px;"), "label" => "Submit"))->getForm();

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $date_time = $form["date_time"]->getData();
            $fk_user_id = $user;
            $fk_dish_id = $form["fk_dish_id"]->getData();

            $meal->setDateTime($date_time);
            $meal->setFkUserId($fk_user_id);
            $meal->setFkDishId($fk_dish_id);
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($meal);
            $entityManager->flush();



            return $this->redirectToRoute('schedule_meals_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('schedule_meals/edit.html.twig', [
            'meal' => $meal,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'schedule_meals_delete', methods: ['POST'])]
    public function delete(Request $request, Meals $meal): Response
    {
        if ($this->isCsrfTokenValid('delete'.$meal->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($meal);
            $entityManager->flush();
        }

        return $this->redirectToRoute('schedule_meals_index', [], Response::HTTP_SEE_OTHER);
    }
}

Project/mealPlanner/templates/schedule_meals/_delete_form.html.twig
<form method="post" action="{{ path('schedule_meals_delete', {'id': meal.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ meal.id) }}">
    <button class="btn">Delete</button>
</form>

Project/mealPlanner/templates/schedule_meals/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Project/mealPlanner/templates/schedule_meals/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Meals{% endblock %}

{% block body %}

    <div class="container py-4">
    <h1>Edit Meals</h1>

    {{ form_start(form) }}
    {{form_widget(form)}}
    {{ form_end(form) }}
    <a href="{{ path('schedule_meals_index') }}" class=" btn btn-warning">back to list</a>
</div>
{% endblock %}

Project/mealPlanner/templates/schedule_meals/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Meals index{% endblock %}

{% block body %}
         <div id="planner" class="container my-5 border-0">



            <div class="row mb-md-4 mb-2 ">

                <div class="mb-3 mb-lg-0 col-sm-12 col-md-12 col-lg-3 text-lg-end">
                    <h1 class="d-inline d-lg-block"><span class="badge bg-dark text-white">Today</span></h1>
                    <span class="fst-italic">{{ today }}</span>
                </div>

                <div class="mb-2 col-sm-12 col-md-4 col-lg-3 meal-outside">
                    <ul class="list-group list-group-flush rounded-3">
                        <li class="list-group-item border-dark bg-transparent">
                            <h3 class="d-inline d-md-block d-xl-inline text-start mb-0 mealtype">Breakfast</h3>
                            <small class="text-muted float-end float-md-start float-xl-end fst-italic"></small>
                        </li>
                        <li class="list-group-item bg-transparent">
                            <ul class="list-unstyled">
                                <li>
                                {% for meal in result %}
                                {% if meal.date_time >= breakfast_start and meal.date_time < lunch_start %}
                                    <h4 class="h6 mt-2 ms-1">{{meal.date_time}}</h4>
                                    <h4 class="h6 mt-2 ms-1">{{meal.dish_name}}</h4>
                                    <img class="img-thumbnail border-dark" src="{{ asset( 'img/dishes/' ~ meal.image) }}" />
                                    <a href="{{ path('schedule_meals_edit', {'id': meal.id}) }}" class="my-2 btn btn-warning">edit entry</a>
                                {% endif %}
                                {% endfor %}
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>





                <div class="mb-2 col-sm-12 col-md-4 col-lg-3 meal-middle">
                    <ul class="list-group list-group-flush rounded-3">
                        <li class="list-group-item border-dark bg-transparent">
                            <h3 class="d-inline d-md-block d-xl-inline text-start mb-0 mealtype">Lunch</h3>
                            <small class="text-muted float-end float-md-start float-xl-end fst-italic"></small>
                        </li>
                        <li class="list-group-item bg-transparent">
                            <ul class="list-unstyled">
                                <li>
                               {% for meal in result %}
                                {% if meal.date_time >= lunch_start and meal.date_time < dinner_start  %}
                                    <h4 class="h6 mt-2 ms-1">{{meal.date_time}}</h4>
                                    <h4 class="h6 mt-2 ms-1">{{meal.dish_name}}</h4>
                                    <img class="img-thumbnail border-dark" src="{{ asset( 'img/dishes/' ~ meal.image) }}" />
                                    <a href="{{ path('schedule_meals_edit', {'id': meal.id}) }}"  class="my-2 btn btn-warning">edit entry</a>
                                {% endif %}
                                {% endfor %}
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>





                <div class="mb-2 col-sm-12 col-md-4 col-lg-3 meal-outside">
                    <ul class="list-group list-group-flush rounded-3">
                        <li class="list-group-item border-dark bg-transparent">
                            <h3 class="d-inline d-md-block d-xl-inline text-start mb-0 mealtype">Dinner</h3>
                            <small class="text-muted float-end float-md-start float-xl-end fst-italic"></small>
                        </li>
                        <li class="list-group-item bg-transparent">
                            <ul class="list-unstyled">
                                <li>
                                {% for meal in result %}
                                {% if meal.date_time >= dinner_start and meal.date_time < night_start   %}
                                    <h4 class="h6 mt-2 ms-1">{{meal.date_time}}</h4>
                                    <h4 class="h6 mt-2 ms-1">{{meal.dish_name}}</h4>
                                    <img class="img-thumbnail border-dark" src="{{ asset( 'img/dishes/' ~ meal.image) }}" />
                                    <a href="{{ path('schedule_meals_edit', {'id': meal.id}) }}"  class="my-2 btn btn-warning">edit entry</a>
                                {% endif %}
                                {% endfor %}
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

            </div>
  </div>


{% endblock %}

Project/mealPlanner/templates/schedule_meals/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Meals{% endblock %}

{% block body %}

<div class="container py-4">
    <h1>Schedule a new meal</h1>
  {{ form_start(form) }}
    {{form_widget(form)}}
    {{ form_end(form) }}
</div>
{% endblock %}

Project/mealPlanner/templates/schedule_meals/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Meals{% endblock %}

{% block body %}
    <h1>Meals</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ meal.id }}</td>
            </tr>
            <tr>
                <th>Date_time</th>
                <td>{{ meal.dateTime ? meal.dateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('schedule_meals_index') }}">back to list</a>

    <a href="{{ path('schedule_meals_edit', {'id': meal.id}) }}">edit</a>

    {{ include('schedule_meals/_delete_form.html.twig') }}
{% endblock %}